paths:
  train_csv: data/raw/train.csv
  test_csv: data/raw/test.csv
  supplements: []        # e.g., ["data/raw/dataset1.csv","data/raw/dataset3.csv","data/raw/dataset4.csv"]
  processed_dir: data/processed
  interim_dir: data/interim
  models_dir: data/processed/models
  features_file: data/processed/features.parquet
  features_meta: data/processed/features_meta.json
  preprocessor_state: data/processed/preprocessor_state.joblib

random_seed: 42
n_jobs: -1

targets: ["Tg","FFV","Tc","Density","Rg"]
smiles_col: "SMILES"

features:
  use_rdkit_descriptors: true
  use_morgan_fp: true
  morgan_radius: 2
  morgan_nbits: 1024

preprocessing:
  scale: true
  variance_threshold: 0.0
  corr_threshold: 0.90
  clip_outliers: false

selection:
  top_k_per_target: 60
  min_labels: 500

imputation:
  min_missing_for_nn: 30
  min_known_for_nn: 50
  simple_strategy: "median"

training:
  n_splits: 5
  num_boost_round: 4000
  early_stopping_rounds: 200

xgb_params_default:
  tree_method: "hist"
  learning_rate: 0.03
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 1.0
  min_child_weight: 1.0
